// Cloudflare Workers entry — wraps the OpenNext-generated handler.
//
// Responsibilities:
// 1. Stash `env` on globalThis so src/lib/db/adapters/workersKvStore.js can
//    reach the DB_KV binding (OpenNext also exposes it via
//    Symbol.for("__cloudflare-context__") — both are consulted).
// 2. After the Next.js handler resolves, attach the adapter's dirty-aware
//    snapshot flush to ctx.waitUntil so in-flight KV writes survive the end
//    of the request. The hook is set by the sql.js adapter via
//    globalThis.__9R_DB_FLUSH_SOON__ (separate bundle instances).
//
// wrangler.jsonc `main` points here; the OpenNext bundle at
// .open-next/worker.js is generated by `npm run build:workers` /
// `deploy:workers` before wrangler bundles this file.
import handler from "../.open-next/worker.js";

export default {
  async fetch(request, env, ctx) {
    try {
      globalThis.__9R_CLOUDFLARE_ENV__ = env;
      return await handler.fetch(request, env, ctx);
    } finally {
      const flush = globalThis.__9R_DB_FLUSH_SOON__;
      if (typeof flush === "function") {
        try {
          const p = flush();
          if (p && typeof p.then === "function" && ctx && typeof ctx.waitUntil === "function") {
            ctx.waitUntil(p);
          }
        } catch {
          // durability is best-effort; never fail the response over it
        }
      }
    }
  },
};
